package JPListDemo::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'JPListDemo::Schema',
    
    
);

=head1 NAME

JPListDemo::Model::JPListDemoDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<JPListDemo>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<JPListDemo::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Sheeju Alex

=head1 LICENSE

This JPListDemo is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
